global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

# Alertmanager configuration (can be uncommented if needed)
# alerting:
#   alertmanagers:
#   - static_configs:
#     - targets: ['alertmanager:9093']

# Rule files to load (can be uncommented if needed)
# rule_files:
#   - "alert_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'backend'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['backend:3000']
    
  # Add metrics endpoint for frontend if it exposes metrics
  # - job_name: 'frontend'
  #   metrics_path: '/metrics'
  #   static_configs:
  #     - targets: ['frontend:80']
    
  - job_name: 'influxdb'
    static_configs:
      - targets: ['influxdb:8086']
      
  # Node exporter for system metrics (if added in future)
  # - job_name: 'node-exporter'
  #   static_configs:
  #     - targets: ['node-exporter:9100']